### ISSUE TITLE
Help implementing differential drive

### ISSUE THREAD

**Issue by ricardojlrufino** [laurenbramblett/robot_DFD_RL#1]
Hi, I'm trying to implement a 2 wheel robot simulator but I'm stuck on the math part.

I read some of the theory, but as it's been a while since I left college, I'm not acknowledging the terms.

Basically I have 2 speed controls for the robot wheels. If I move L_VEL to max. and leave the R_VEL at 0. I believe the rotation he is doing is not correct...

The Code can be edited online:
https://playground.babylonjs.com/#5LD51R#33

**Comment by laurenbramblett** [comment]
Hello!

I am not super familiar with your code, but it does look like it is moving backward. For reference, your total velocity will be
VEL = (L_VEL + R_VEL)/2
with your x-position as 
x+=VELcos(THETA)dt
and y-position (I think you had it as z) as
y-= VELsin(THETA)dt.
and your subsequent heading will be
THETA += (R_VEL-L_VEL)/(VEHICLE_WIDTH)dt
Make sure theta will always stay within pi/-pi
if THETA>pi:
     THETA-=2pi
elif THETA<pi:
     THETA+=2pi
